### Health check

GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzMxMzM5NzUzLCJleHAiOjE3MzEzNDY5NTMsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.nX32XE9Iy7qkE_uLZvNHgfRtLxK1zi_okdCfkALZH8B7p3RtWiJSJnJs3XtyT4inShoBzT3j_b0jpSHQtqmXevdoX1t_ow0SggG-KhZH3P07abGbv44rqSlyd-yts1_2GyxZNMalj5WSUEkOEwfwPz524-RBj9o7YuNwK_-BakRfFwCymVk1HJoXbK44C4LmdR3nsM7FIHMFe9KVXNG5o9-ValVd0ysoPAN4AGvXyAkkIieTiO4z2zncywaVORPDLKI4BwXjcZigIYM8-BTIYBfSW0RKntaa_CS8erd6R23DfSRLihxeXHMt9S0-Z8T2Yudz8A0dzTiO9Ts_vMPDsg

### GET task by ID
GET http://localhost:3000/v1/tasks/cm34k39zh0002ii6chxkr0x1o HTTP/1.1
Authorization: Bearer 

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzMxMzM5NzUzLCJleHAiOjE3MzEzNDY5NTMsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.nX32XE9Iy7qkE_uLZvNHgfRtLxK1zi_okdCfkALZH8B7p3RtWiJSJnJs3XtyT4inShoBzT3j_b0jpSHQtqmXevdoX1t_ow0SggG-KhZH3P07abGbv44rqSlyd-yts1_2GyxZNMalj5WSUEkOEwfwPz524-RBj9o7YuNwK_-BakRfFwCymVk1HJoXbK44C4LmdR3nsM7FIHMFe9KVXNG5o9-ValVd0ysoPAN4AGvXyAkkIieTiO4z2zncywaVORPDLKI4BwXjcZigIYM8-BTIYBfSW0RKntaa_CS8erd6R23DfSRLihxeXHMt9S0-Z8T2Yudz8A0dzTiO9Ts_vMPDsg

### GET project by ID
GET http://localhost:3000/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1
