### Health check

GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM1ODM4ODk5LCJleHAiOjE3MzU4NDYwOTksInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.WOUFGS4xul0cm5iw-gTmCZt316urorvej3sMAuLp2nC5I9aOIkqZ1L6LrHBFw_50j4ICGUVhehZlgDTRnYSwxNuoK-IgRga_Q_d9MSwt_QGUWBpoo6LGJYpMOo9T0oFdHR60BP_Sr_-sZco8E39n2RvaShTjkLcHTJHSOkzoBpeNshOG4PmaAv8eRJLziwTlzLzcwkVCewS7S3yXTsiDdaGznehufFjpuo3MMPxCrcJFDKpdL1fqicPmHX1TRRad6m6TF3bSkd0WRLVDr1eJnAbCdyDnFxDaEXAXIckr4qeR7-lML--NjlyZ8iM613pXah3EqyeWeuRkJc1KFvwVzA

### GET task by ID
GET http://localhost:3000/v1/tasks/cm34k39zh0002ii6chxkr0x1o HTTP/1.1
Authorization: Bearer 

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM1ODM4ODk5LCJleHAiOjE3MzU4NDYwOTksInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.WOUFGS4xul0cm5iw-gTmCZt316urorvej3sMAuLp2nC5I9aOIkqZ1L6LrHBFw_50j4ICGUVhehZlgDTRnYSwxNuoK-IgRga_Q_d9MSwt_QGUWBpoo6LGJYpMOo9T0oFdHR60BP_Sr_-sZco8E39n2RvaShTjkLcHTJHSOkzoBpeNshOG4PmaAv8eRJLziwTlzLzcwkVCewS7S3yXTsiDdaGznehufFjpuo3MMPxCrcJFDKpdL1fqicPmHX1TRRad6m6TF3bSkd0WRLVDr1eJnAbCdyDnFxDaEXAXIckr4qeR7-lML--NjlyZ8iM613pXah3EqyeWeuRkJc1KFvwVzA

### GET project by ID
GET http://localhost:3000/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1

