### Health check

GET http://localhost:3000/health HTTP/1.1

### GET tasks
GET http://localhost:3000/v1/tasks?perPage=3&prevCursor=MjAyMC0wMS0wMlQxNzo0NDozNi44ODVa HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM4NzY2NjQ2LCJleHAiOjE3Mzg3NzM4NDYsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.JPZlC4NBGz9jSjwUUl0REvPEr-h1cUM51GKIaigsn2YPIh76fici5FV918FPr4ueC7wTzg3bL74wC5C-ZIBRiAZriLoXfwFR-sWC22N1YEauAcgA6fElK3xNjwcivVGx-Zy9BkmM1ohd3zQWSErR9KeZyYUMNB7uBIMIADvXBKsWteHHiozh7mxX22cxTg8kHqmCuLrd_s1gNs0ti9vGu78I-LRcVnyWA-4d232jMt9hqCENpkAZq7bvHr4yORQb0cYbxMh9slnYVZV0RqqmIYvrY6ikGYvQgeELQWirARA1v8mVMaCIBbVnqSnF4G1zKdQ4Hhcccg0QrxqsDtTK8w

### GET task by ID
GET http://localhost:3000/v1/tasks/cm34k39zh0002ii6chxkr0x1o HTTP/1.1
Authorization: Bearer 

### GET projects
GET http://localhost:3000/v1/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjZZRDhLdEpfdzBZTWttQXZhVUlNSiJ9.eyJpc3MiOiJodHRwczovL2Rldi1ubHl5ZHhwdGNwZWxoNTNuLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwMDU0MTY2NzczNTg2OTkyMzc1OSIsImF1ZCI6WyJ0YXNrLW1hbmFnZXItYXBpIiwiaHR0cHM6Ly9kZXYtbmx5eWR4cHRjcGVsaDUzbi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzM3NDY5Nzg3LCJleHAiOjE3Mzc0NzY5ODcsInNjb3BlIjoib3BlbmlkIGVtYWlsIiwiYXpwIjoiS3RaMHBPcHBqRkRaUG1xOE9lR21vSE1VZTRxdG1ROUEifQ.bDEdU6J23jlq2k2VXA1Q4oPdI_oXC_vtpb_8Hc_-cSgsUalNromxM69OZvFt2BqjstmzK4-zrT4zJQBfLMWzmBfgT-sR-jEfznXDMyF0i-eIdivkQAvBFCkxzXNK3EB8xVGvpGgAfIBWF4qIQltkP-mDDNcLRyqVHQsWrLM5HTZNQ3UxjzBBgcAyYDSf0Zb7e2yp7j_nj8sp7dCwnxpbTdTrOpMltF4f_uo-TgQ3jig5-NM_itPxLyrfmNCUn0_vV-AaDZ33z41NMlBgo2Bn3z8FpglNwlKa216gUuW01XFXlVaIKmJtaUxmyCrMNBqdGSyvivR8DHXk6HW48gCbBw

### GET project by ID
GET http://localhost:3000/v1/projects/1 HTTP/1.1

### GET project's tasks
GET http://localhost:3000/v1/projects/1/tasks HTTP/1.1

